# Use the official Postgres image
FROM postgres:latest

# Set environment variables for database initialization
ENV POSTGRES_USER=wifi
ENV POSTGRES_PASSWORD=wifi
ENV POSTGRES_DB=wifi

# Optional: Add custom initialization SQL scripts
# COPY init.sql /docker-entrypoint-initdb.d/
