  #   - name: 'Deploy to Cloud Run'
    #   - id: docker-push-tagged
    #     name: Tag Docker image and push to Google Artifact Registry
    #     uses: docker/build-push-action@v2
    #     with:
    #       push: true
    #       tags: "${{ env.REGION }}-docker.pkg.dev/rpi-hub-438905/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"


name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "rpi-hub-438905"
  REGION: "asia-southeast1"
  SERVICE: "my-cloud-run-service" # Cloud Run service name
  WORKLOAD_IDENTITY_POOL_ID: "projects/422041495987/locations/global/workloadIdentityPools/github"
  WORKLOAD_IDENTITY_PROVIDER: "projects/422041495987/locations/global/workloadIdentityPools/github/providers/my-repo"
  REPO: "malone-deployment/expert-winner"
  REPOSITORY_NAME: "piso-wifi-repository"
  IMAGE_NAME: "bitch-image"
  SERVICE_EMAIL: "estavillofretz-developer-rpi-h@rpi-hub-438905.iam.gserviceaccount.com"
  SERVICE_NAME: "estavillofretz-developer@rpi-hub-438905.iam.gserviceaccount.com"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"

      - name: "Docker Auth"
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "${{ env.REGION }}-docker.pkg.dev"

      - name: 'Build and Push Container'
          run: |-
            DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/rpi-hub-438905/piso-wifi-repository/sculpturelist:${{ github.sha }}"
            docker build --tag "${DOCKER_TAG}" .
            docker push "${DOCKER_TAG}"

  

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          #   image: "${{ env.REGION }}-docker.pkg.dev/rpi-hub-438905/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          image: "${{ env.REGION }}-docker.pkg.dev/rpi-hub-438905/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"


      - name: "Show output"
        run: |
          echo ${{ steps.deploy.outputs.url }}
