name: 'Build and Deploy Postgres to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }} # Google Cloud project ID
  REGION: ${{ secrets.REGION }} # Google Cloud region
  SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }} # Service account email
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }} # Workload Identity Provider
  GAR_REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }} # Artifact Registry repository

  POSTGRES_SERVICE: 'postgres-service' # Cloud Run service name
  BACKEND_SERVICE: 'backend-service' # Cloud Run service name
  WEB_SERVICE: 'web-service' # Cloud Run service name

  POSTGRES_IMAGE: 'postgres-image' # Docker image name
  BACKEND_IMAGE: 'backend-image'
  WEB_IMAGE: 'web-image'

  POSTGRES_USER: 'wifi' # Database username
  POSTGRES_PASSWORD: 'wifi' # Database password
  POSTGRES_DB: 'wifi' # Database name

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service_account: '${{ env.SERVICE_EMAIL }}'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      # Build and deploy the POSTGRES service to Cloud Run
      - name: 'Build and Push Image to Artifact Registry'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.POSTGRES_IMAGE }}:${{ github.sha }}"
          docker build postgres/ -t "${DOCKER_TAG}" \
            --build-arg POSTGRES_USER="${{ env.POSTGRES_USER }}" \
            --build-arg POSTGRES_PASSWORD="${{ env.POSTGRES_PASSWORD }}" \
            --build-arg POSTGRES_DB="${{ env.POSTGRES_DB }}"
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        run: |-
          gcloud run deploy "${{ env.POSTGRES_SERVICE }}" \
            --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.POSTGRES_IMAGE }}:${{ github.sha }}" \
            --region "${{ env.REGION }}" \
            --service-account "${{ env.SERVICE_EMAIL }}" \
            --allow-unauthenticated \
            --port 5432 \
            --memory "512Mi" \
            --cpu "1"

      - name: 'Show Cloud Run URL'
        run: |-
          echo "Service URL: https://$(gcloud run services describe ${{ env.POSTGRES_SERVICE }} --region=${{ env.REGION }} --format='value(status.url)')"
        timeout: 1200s

      # Build and deploy the BACKEND service to Cloud Run
      - name: 'Build and Push Image to Artifact Registry'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/rpi-hub-438905/${{ env.GAR_REPOSITORY_NAME }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}"  
          docker build apps/backend/Dockerfile -t "${DOCKER_TAG}"
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy "${{ env.BACKEND_SERVICE }}" \
          --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}" \
          --update-labels managed-by=github-actions,commit-sha="${{ github.sha }}" \
          --region "${{ env.REGION }}" \
          --service-account "${{ env.SERVICE_EMAIL }}" \
          --allow-unauthenticated

      - name: 'Show output'
        run: |
          echo "Cloud Run service deployed to:"
          echo "${{ steps.deploy.outputs.url }}"

      # Build and deploy the WEB service to Cloud Run
      - name: 'Build and Push Image to Artifact Registry'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/rpi-hub-438905/${{ env.GAR_REPOSITORY_NAME }}/${{ env.WEB_IMAGE }}:${{ github.sha }}"  
          docker build apps/web/Dockerfile -t "${DOCKER_TAG}"
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy "${{ env.WEB_SERVICE }}" \
          --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.WEB_IMAGE }}:${{ github.sha }}" \
          --update-labels managed-by=github-actions,commit-sha="${{ github.sha }}" \
          --region "${{ env.REGION }}" \
          --service-account "${{ env.SERVICE_EMAIL }}" \
          --allow-unauthenticated

      - name: 'Show output'
        run: |
          echo "Cloud Run service deployed to:"
          echo "${{ steps.deploy.outputs.url }}"
